### ISSUE TITLE
Message text cut off

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-ios#18]
This was taken after I posted the message "Test" twice in a row:

![img_1a0fdf496d25-1](https://user-images.githubusercontent.com/7308599/40215181-e39d33e4-5a13-11e8-9bc2-bd68eeaa14cd.jpeg)

Then I sent "Still testing":

![img_0d5bf759b1ae-1](https://user-images.githubusercontent.com/7308599/40215201-1340c048-5a14-11e8-9e80-5677ab9a76b6.jpeg)

**Comment by nickyhajal** [comment]
Should be fixed in next update, yayy :)
