### ISSUE TITLE
New color for RSVP Cancel

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-ios#20]
Is there a better color in the new palette for the cancel button?

![img_6b8037674a69-1](https://user-images.githubusercontent.com/7308599/40215379-fcc8f32a-5a14-11e8-80cb-b8cf2eed1c01.jpeg)

**Comment by nickyhajal** [comment]
Yeah, that's the old color -  only problem with staying on brand completely is that the red is very close to the orange:

![iphone_6s_-_11_3](https://user-images.githubusercontent.com/1079625/40241036-9083e93e-5a7f-11e8-921c-7f0692ed1e20.jpg)

Any thoughts?

**Comment by ibwatson** [comment]
Could we use gray instead? Less alert-y but would provide good contrast.
-- 
Isaac B Watson
Kickass Conferences, LLC
(Creative conference design and production services)
503.944.9271

Website: ibwatson.com
 <http://ibwatson.com/>Twitter: @ibwatson <http://twitter.com/ibwatson>
Instagram: @ibwatsongram <http://instagram.com/ibwatsongram>

**Comment by nickyhajal** [comment]
Yep yep, good call!
