### ISSUE TITLE
Update key images

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-ios#24]
Would be great to update these with photos from 2017 if possible. We can have Jedd pull options if needed.

![img_404508a6849c-1](https://user-images.githubusercontent.com/7308599/40244427-b320ded2-5a77-11e8-9e88-5a3c611b4952.jpeg)

**Comment by nickyhajal** [comment]
Could we get Jedd on this asap if we want to do it before launch? (Just because we should get the app into review soon)
