### ISSUE TITLE
Notification count placement is off

### ISSUE THREAD

**Issue by stevenp** [nickyhajal/wds-ios#29]
iPhone X, iOS 11.4 beta (which will likely be widely released before WDS, not sure if this happens on 11.3).

This is more than an appearance glitch because if someone comes into the WDS app from Spotlight search on their phone (typing WDS in the search box) the OS "back to search" link will overlap the notification count

![img_4041](https://user-images.githubusercontent.com/181589/40255094-cc54da52-5a9a-11e8-867a-687da9c70967.PNG)

**Comment by nickyhajal** [comment]
Thanks! Updated and should be available and the next push!
