### ISSUE TITLE
Pull-to-refresh text bleeds into content area on refresh

### ISSUE THREAD

**Issue by stevenp** [nickyhajal/wds-ios#30]
I realize this is more of a design polish thing rather than a bug. How would you feel about adding a label to GitHub for that?

https://www.dropbox.com/s/99imo288jxbggaq/ScreenRecording_05-18-2018%2013-05-41.MP4?dl=0

**Comment by nickyhajal** [comment]
Agreed! Just made a `polish` label.

As for this one, I had noticed it too (#11) and it should be fixed in the next push!
