### ISSUE TITLE
WDS Team messages not push-notifying

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-ios#37]
This shows me the last notification from a 1:1 message, but there were at least 4 messages received from WDS Team that came in after that one.

![img_16dd8ec08d4c-1](https://user-images.githubusercontent.com/7308599/40337760-3c13e184-5d26-11e8-9496-13eaef04cae4.jpeg)

**Comment by nickyhajal** [comment]
Great point - need to update the push credentials for the process that handles that
