### ISSUE TITLE
Occasional crashes in Communities views

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-ios#4]
Tapping the X to the left of the filter options occasionally crashes the app. I haven't been able to find any consistency in how this works, though.

**Comment by nickyhajal** [comment]
Thank you for these reports! Will get on them shortly

**Comment by nickyhajal** [comment]
I was able to reproduce this before and am not any longer even though I didn't specifically fix it. I did make some general updates to how communities are handled so it's possible that resolved the underlying issue here. 

Going to close this but lets keep an eye on it!
