### ISSUE TITLE
Schedule offset

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-ios#5]
When you select a day from the schedule page, the schedule then becomes offset by one day, showing Friday's schedule when you've chosen Saturday (but listed as Saturday).

![img_3967](https://cloud.githubusercontent.com/assets/7308599/7566343/094ed530-f7ab-11e4-903c-4cddf0927cb1.PNG)

**Comment by nickyhajal** [comment]
Fixed!
