### ISSUE TITLE
Stuttered scrolling through posts

### ISSUE THREAD

**Issue by ibwatson** [nickyhajal/wds-ios#6]
I've noticed that when scrolling downward, at certain points it will start stuttering and then spring back up to the top of a certain post, not allowing you to scroll any further. The one in the screen shot below seems to be the most consistent. I'm not sure if it's the overall length or the way the app loads the content, but I can definitely see from the scroll bar that there's more content below it.

![img_3968](https://cloud.githubusercontent.com/assets/7308599/7566370/3f445a16-f7ab-11e4-97bb-f5a02760447a.PNG)

**Comment by nickyhajal** [comment]
Fixed!
